name: lint
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{js,md}
          only_changed: True
          commit_message: "style: prettier"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
